name: codecov
on: [push]
jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Generate coverage report
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: bc88c9f0-a77f-4b6c-90e6-51786d347af2
          file: ./coverage.txt
          flags: unittests
          name: codecov-configcli
